const date = document.getElementById('date');
let yesterday = ( d => new Date(d.setDate(d.getDate()-1)) )(new Date);
const month = new Array();
month[0] = "January";
month[1] = "February";
month[2] = "March";
month[3] = "April";
month[4] = "May";
month[5] = "June";
month[6] = "July";
month[7] = "August";
month[8] = "September";
month[9] = "October";
month[10] = "November";
month[11] = "December";
date.innerHTML = `${month[yesterday.getMonth()]} ${yesterday.getDate()}, ${yesterday.getFullYear()}`;
