<footer class="main-footer">
  <div class="container">
    <h2>Sourced Media Links</h2>
    <ul>
      <li><a href="http://video.foxbusiness.com/v/3034387934001/?#sp=show-clips" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/fox-dark.png" alt=""></a></li>
      <li><a href="https://www.bloomberg.com/news/articles/2015-03-18/penny-stock-guru-tim-sykes-embraces-role-of-rich-douche-bag-" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/bloomberg-dark.png" alt=""></a></li>
      <li><a href="https://www.forbes.com/sites/elainepofeldt/2014/11/28/how-tim-sykes-created-his-multi-million-dollar-blog/#56e25dd84908" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/forbes-dark.png" alt=""></a></li>
      <li><a href="http://money.cnn.com/2013/12/16/investing/penny-stock-trader-millionaire/index.html" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/cnnmoney.png" alt=""></a></li>
      <li><a href="https://www.inc.com/john-rampton/interview-with-timothy-sykes-the-man-who-wants-everyone-to-be-a-millionaire.html" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/inc.png" alt=""></a></li>
      <li><a href="http://www.businessinsider.com/timothy-sykes-profitly-penny-stocks-instagram" target="_blank" rel="nofollow"><img src="<?php echo IMG; ?>/business_insider_dark.png" alt=""></a></li>
    </ul>
    <p>DISCLAIMER: Before you proceed with this course, make sure you read and understand the following disclaimer.</p>
    <p>This manual is for informational and entertainment purposes only. The author is not an investment advisor, financial adviser, or broker. The material contained herein is not intended as investment advice. If you wish to obtain personalized investment advice, you should consult with a Certified Financial Planner (CFP). All statements made in this manual are based on the author's own opinions. Neither the author nor the publisher warrants or assumes any responsibility for the accuracy of the statements or information contained in this manual, and specifically disclaims the accuracy of any data, including stock prices and stock performance histories. No mention of a particular security or instrument herein constitutes a recommendation to buy or sell that or any security or instrument, nor does it mean that any particular security instrument, portfolio of securities, transaction or investment strategy is suitable for any specific individual. Neither the author nor the publisher can assess, verify, or guarantee the accuracy, adequacy, or completeness of any information, the suitability or profitability of any particular investment or methodology, or the potential value of any investment or informational source. READERS OF THIS BEAR THE SOLE RESPONSIBILITY FOR THEIR OWN INVESTMENT DECISIONS. NEITHER THE AUTHOR NOR THE PUBLISHER IS RESPONSIBLE FOR ANY LOSSES DUE TO INVESTMENT DECISIONS MADE BASED UPON INFORMATION PROVIDED HEREIN. At the time of writing, neither the author nor the publisher has a position in any of the stocks mentioned in this manual.</p>
    <p>By proceeding with reading this course, you affirm that you have read and understand the above disclaimer.</p>
    <p><strong>Millionaire Media 80 S.W. 8th Street Suite 2000 Miami, Florida 33130 United States</strong></p>
    <small><span>©2020 TimothySykes™ All Rights Reserved.</span> <span class="main-footer__nav-wrap"><a href="http://timsykesbook.com/legal/terms-of-service/" target="_blank" rel="nofollow">Terms of Use</a> | <a href="http://timsykesbook.com/legal/privacy-policy/" target="_blank" rel="nofollow">Privacy Policy</a>  | <a href="#" class="openPopup" data-popup="contact-us" rel="nofollow">Contact Us</a></span></small>
  </div>
</footer>